In [1]:
import numpy as np
import onnxruntime as ort
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
iris = load_iris()
X, y = iris.data, iris.target
_, X_test, _, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_test_f32 = X_test.astype(np.float32)
print(f"Test samples: {len(X_test)}")

Test samples: 30


In [3]:
models = {
    "Random Forest": "models/iris_rf.onnx",
    "CatBoost": "models/iris_catboost.onnx",
    "IrisNet": "models/iris_nn.onnx",
}

for name, path in models.items():
    sess = ort.InferenceSession(path)
    input_name = sess.get_inputs()[0].name
    outputs = sess.run(None, {input_name: X_test_f32})

    if outputs[0].ndim == 2 and outputs[0].shape[1] > 1:
        preds = outputs[0].argmax(axis=1)
    else:
        preds = outputs[0].flatten().astype(np.int64)

    print("=" * 40)
    print(f"{name} (ONNX)")
    print("=" * 40)
    print(f"Accuracy: {accuracy_score(y_test, preds):.4f}")
    print(classification_report(y_test, preds, target_names=iris.target_names))
    print(f"Confusion matrix:\n{confusion_matrix(y_test, preds)}\n")

Random Forest (ONNX)
Accuracy: 1.0000
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

CatBoost (ONNX)
Accuracy: 1.0000
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

IrisNet (ONNX)
Accuracy: 1.0000
              precision